on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Test
permissions: write-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: install courtney
        run: go install github.com/dave/courtney@latest
      - name: install dependencies
        run: go mod tidy
      - name: generate test coverage
        run: courtney -o cover.out ./...
      - name: install deepsource
        run: curl https://deepsource.io/cli | sh
      - name: run deepsource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: ./bin/deepsource report --analyzer test-coverage --key go --value-file ./cover.out
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
